name: CI

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # https://crontab.guru/#30_5,17_*_*_*
    - cron: "0 0 * * *"
  pull_request:
  push:
  workflow_dispatch:

jobs:
  ci:
    name: CI
    uses: deemp/workflows/.github/workflows/nix-ci.yaml@main
    secrets: inherit
