name:                clerk
version:             0.1.0.1
github:              "deemp/clerk"
license:             BSD3
author:              "Danila Danko, Nickolay Kudasov"
maintainer:          "Danila Danko"
copyright:           "Danila Danko, Nickolay Kudasov"
category:            "spreadsheet"
synopsis:            "Declaratively describe spreadsheets and generate xlsx"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            value

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/deemp/clerk#readme>

default-extensions:
- DataKinds
- DeriveFunctor
- FlexibleContexts
- FlexibleInstances
- OverloadedStrings
- GeneralizedNewtypeDeriving
- RankNTypes
- ImportQualifiedPost
- InstanceSigs
- NamedFieldPuns
- RecordWildCards
- TupleSections
- MonoLocalBinds
- TypeSynonymInstances
- DuplicateRecordFields

dependencies:
- base >= 4.9.0.0 && < 5.0
- mtl >= 2.1
- transformers >= 0.3.0.0
- text >= 0.11.3.1
- xlsx >= 1.1.0.1
- bytestring >= 0.10.8.0
- lens >= 3.8 && < 5.3
- time >= 1.4.0.1
- containers >= 0.5.0.0
- data-default >= 0.7.1.1

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src