name: clerk
version: 0.2.0.3
github: "deemp/clerk"
license: BSD3
author: "Danila Danko, Nickolay Kudasov"
maintainer: "Danila Danko"
copyright: "Danila Danko, Nickolay Kudasov"
category: "spreadsheet"
synopsis: "Declaratively describe spreadsheets"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            value

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: |
  `clerk` provides a Haskell eDSL and a library for declaratively describing the spreadsheets. 
  `clerk` is built on top of the [xlsx](https://hackage.haskell.org/package/xlsx) package 
  and extends upon the [work](https://youtu.be/1xGoa-zEOrQ) of Nickolay Kudasov.
  See the [README](https://github.com/deemp/clerk#readme) for an example of `clerk` usage and further info.

dependencies:
  - base >= 4.9 && < 5.0

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

tests:
  docs:
    main: test/Docs.hs
    dependencies:
      - turtle
      - string-interpolate
      - text
    build-tools: lima:lima ^>= 0.1

library:
  source-dirs: src
  dependencies:
    - bytestring
    - containers
    - data-default
    - microlens
    - mtl
    - text
    - time
    - transformers
    - xlsx

executables:
  example1:
    main: app/Example1.hs
    dependencies: &example
      - clerk
      - microlens
      - text
      - xlsx
  example2:
    main: app/Example2.hs
    dependencies: *example
